export const ROUTES = {
  auth: {
    signIn: "/auth/sign-in",
    register: "/auth/register",
    verifyEmail: "/auth/verify-email",
    forgotPassword: "/auth/forgot-password",
    /** PKCE redirect target for `resetPasswordForEmail` (email link lands here). */
    recovery: "/auth/recovery",
    updatePassword: "/auth/update-password",
    /** @deprecated Use `updatePassword`; kept for bookmarks. */
    changePassword: "/auth/change-password",
  },
  marketing: {
    pricing: "/#pricing",
  },
  dashboard: {
    main: "/dashboard",
    staff: "/dashboard/staff",
    staffAdd: "/dashboard/staff/add",
    staffAddReview: "/dashboard/staff/add/review",
    staffEdit: (membershipId: string) => `/dashboard/staff/${membershipId}/edit`,
    stock: "/dashboard/stock",
    stockAdd: "/dashboard/stock/add",
    stockBulkAdd: "/dashboard/stock/bulk-add",
    stockBatch: (batchId: string) => `/dashboard/stock/batches/${batchId}`,
    stockProductEdit: (productId: string) => `/dashboard/stock/products/${productId}/edit`,
    stockExpiring: "/dashboard/stock/expiring",
    sales: "/dashboard/sales",
    salesAdd: "/dashboard/sales/add",
    insights: "/dashboard/insights",
    productCategories: "/dashboard/product-categories",
    pay: "/dashboard/pay",
    expenses: "/dashboard/expenses",
    payTransaction: (paymentId: string) => `/dashboard/pay/transactions/${paymentId}`,
    organization: "/dashboard/organization",
    organizationBranches: {
      new: "/dashboard/organization/branches/new",
      detail: (branchId: string) => `/dashboard/organization/branches/${branchId}`,
      edit: (branchId: string) => `/dashboard/organization/branches/${branchId}/edit`,
    },
    onboarding: {
      root: "/dashboard/onboarding",
      locationDetails: "/dashboard/onboarding/location-details",
      license: "/dashboard/onboarding/license",
      review: "/dashboard/onboarding/review",
    },
  },
  demoSuccess: "/dashboard/demo/success",
  settings: "/dashboard/settings",
  billingPortal: "/dashboard/settings/billing",
  features: "/dashboard/features",
} as const;
