export const ROUTES = {
  auth: {
    signIn: "/auth/sign-in",
    register: "/auth/register",
    changePassword: "/auth/change-password",
  },
  dashboard: {
    main: "/dashboard",
    staff: "/dashboard/staff",
    staffAdd: "/dashboard/staff/add",
    staffAddReview: "/dashboard/staff/add/review",
    stock: "/dashboard/stock",
    stockAdd: "/dashboard/stock/add",
    stockBatch: (batchId: string) => `/dashboard/stock/batches/${batchId}`,
    stockExpiring: "/dashboard/stock/expiring",
    sales: "/dashboard/sales",
    salesAdd: "/dashboard/sales/add",
    insights: "/dashboard/insights",
    pay: "/dashboard/pay",
    onboarding: {
      root: "/dashboard/onboarding",
      pharmacyDetails: "/dashboard/onboarding/pharmacy-details",
      license: "/dashboard/onboarding/license",
      review: "/dashboard/onboarding/review",
    },
  },
  demoSuccess: "/dashboard/demo/success",
  settings: "/dashboard/settings",
  features: "/dashboard/features",
} as const;
